### ISSUE TITLE
add ability to internationalize strings in javascript files

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/vue-intl#11]
Currently, only .vue files are supported. Sometimes it's necessary to internationalize strings in javascript files - see e.g. https://github.com/learningequality/kolibri/issues/1081#issuecomment-289568067

**Comment by rtibbles** [comment]
This is not the case, the vue intl functions can be used anywhere, it's just that the string extraction machinery used in Kolibri does not extract strings from Javascript files.
