### ISSUE TITLE
numbers are not being properly localized

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/vue-intl#17]
For example, this string

```javascript
$trs: {
  progressIndicator: 'Step {currentStep, number} of {totalSteps, number}',
},
```

results in this header:

![image](https://user-images.githubusercontent.com/2367265/42542305-317bc1ea-845b-11e8-92ee-4d09dfd1c3a8.png)

see https://github.com/learningequality/kolibri/pull/4011#discussion_r201514225

**Comment by rtibbles** [comment]
We are archiving this repository in favour of the FormatJS integrated vue-intl plugin: https://github.com/formatjs/formatjs
