### ISSUE TITLE
Cleanup npm package content

### ISSUE THREAD

**Issue by n1kk** [learningequality/vue-intl#27]
Hi, this is not a big issue but I've noticed that `vue-intl` folder in my `node_modules` has `.idea` folder in it and it takes 3mb of space. I think it would be better if you created `.npmignore` file or a `files` section in package.json to exclude all the files that have no reason being in the package itself.

Thanks for the plugin :)

![image](https://user-images.githubusercontent.com/5442968/97221886-d12c2d80-17cd-11eb-81e5-1070d8af6c7c.png)

**Comment by rtibbles** [comment]
We are archiving this repository in favour of the FormatJS integrated vue-intl plugin: https://github.com/formatjs/formatjs
