### ISSUE TITLE
Ownership transfer

### ISSUE THREAD

**Issue by longlho** [learningequality/vue-intl#28]
Hello,

I maintain react-intl & formatjs. I'd love to possibly take over this package. Would it be possible?

@rtibbles @indirectlylit

**Comment by rtibbles** [comment]
Hi @longlho - I think that would probably work for us, as you can see, we've kept it working sufficiently for our purposes, but not so much for external users.

~I'll message you directly to follow up to talk more about it!~

Could you email me directly at richard@learningequality.org so we can discuss further?

**Comment by longlho** [comment]
Thanks a lot @rtibbles !
