### ISSUE TITLE
Leverage Vue's Filters

### ISSUE THREAD

**Issue by DXCanas** [learningequality/vue-intl#3]
Might be worth looking into introducing some new Filters and overriding some functions for these new filters so that we could set a language:

```
vueIntl = require('vue-intl');
vueIntl.lang = 'french';
```

and use it as a filter in the template:

```
<span> {{order | intl-pluralize}}</span>
```

or something of the sort. 

I can see how it would get difficult once more complex language come up, but using the `v-text` directive rather than filters might be more appropriate there.

**Comment by ghost** [comment]
VueJS Filters are deprecated in Vue 2.0.

**Comment by ghost** [comment]
I was incorrect. Filters in bindings are deprecated, but fine within interpolation tags.

**Comment by rtibbles** [comment]
I think there may actually be more mileage in VueJS directives for some of this. One issue I am currently grappling with is how to make the translations properly reactive, and directives might be the best way.

**Comment by vizo** [comment]
Maybe you get some idea from https://github.com/sebastian-software/vue-locale ... It uses filters. But as you said, directives are the way to go.
