### ISSUE TITLE
setLocale not reactive?

### ISSUE THREAD

**Issue by evilru** [learningequality/vue-intl#4]
changing language with Vue.setLocale(lang) on run-time does not affect visible messages. 
am i missing something? 

i have setup a gist to play around with: https://gist.github.com/evilru/70c3f5fe9378573e2b69aac4aec95b1f

**Comment by evilru** [comment]
for what ever reason, it started to work in my project :)

**Comment by rtibbles** [comment]
Glad it worked out. I have been puzzling with the best way to make translations reactive, and haven't come up with a solid solution as yet. My instinct is to make components for the translation functions, but I am still working out what that should look like. Any thoughts welcome!

**Comment by rtibbles** [comment]
The suddenly started working may have had something to do with the latest version bump?

**Comment by evilru** [comment]
No, it looks like it is related to how it is called. I didn't had time to figure out why it started to work.
I keep you updated!
