### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by xpepermint** [learningequality/vue-intl#6]
Hey and thanks for this package. Looks promising ...

I think the README could be better and more understandable. Some of the features doesn't seems to work as they are described. 

Here is an example:
```js
<p>{{ $formatTime(now, {format: 'medium'}) }}</p>
// `medium` is used to format times with hours, minutes, and seconds (from intl-messageformat)
```
You need to dig into the source code to realize that you need to define the `medium` format yourself (I thought that this package is using yahoo's built-in formats).

```js
Vue.registerFormats(locale, {
  time: {
    medium: {hour: '2-digit', minute: '2-digit', second: '2-digit'}
  }
});
```

**Comment by xpepermint** [comment]
It seems that this is for `vue v1`. What about `vue v2`?

**Comment by indirectlylit** [comment]
Hi -

> It seems that this is for vue v1. What about vue v2?

we have a branch for vue2 here, but it's not published to NPM yet: https://github.com/learningequality/vue-intl/tree/vue2

regarding formatting, is there any chance that you need to install the Intl polyfill (https://github.com/andyearnshaw/Intl.js/)?

If that's not the issue, any PRs regarding documentation would be appreciated :)

**Comment by xpepermint** [comment]
@indirectlylit thanks for a quick response. I use the `vue2` branch now.

The `formatTime` method still doesn't recognize the `format` option. I see `[Vue Intl] No time format named: medium` message in the console (server-side and client-side). I have to define this format manually to work.

The `formatRelative` always returns a date and not `X ago` string. The code below works but this plugin does not. I believe it's not the `polyfill` issue.

```
var IntlRelativeFormat = require('intl-relativeformat');
var rf = new IntlRelativeFormat('en-US', {units: 'day'});
var output = rf.format(13123132123);
console.log(output); // -> 16,999 days ago
```

What am I missing? I would appreciate some help.

**Comment by indirectlylit** [comment]
Sorry, I don't know off-hand what the issue is; to be honest we're only just beginning to develop and use this package so it likely has quirks.

However, I can point you to an example of our use of it - hopefully that might help: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach_tools/assets/src/vue/reports/summary-section/index.vue#L115

**Comment by rtibbles** [comment]
Vue2 version should be pushed to npm now, btw.

**Comment by rtibbles** [comment]
Update here, we seem to be missing the relevant locale data required for some of the formatting.

It seems that my port of `react-intl` was incomplete in this regard. Will be updating vue-intl in the nearish future to deal with this issue.

**Comment by rtibbles** [comment]
Note for myself: https://github.com/yahoo/react-intl/blob/d2484c5bd66dd408cfcfed78a06b712e3093679c/scripts/build-data.js

**Comment by rtibbles** [comment]
We are archiving this repository in favour of the FormatJS integrated vue-intl plugin: https://github.com/formatjs/formatjs
